# Paramétrage des serveurs sur lesquels le trafic sera redirigé
# TODO changer le nom de l'upstream "backend"
# nom conseillé : nom_projet_back (attention de bien mettre des '_' et non pas des '-')
upstream choralriff_api { # Premier serveur, la web API
   server cr-api:8080;
}

# TODO changer le nom de l'upstream "frontend"
# nom conseillé : nom_projet_front (attention de bien mettre des '_' et non pas des '-')
upstream choralriff_front { # second server, le front-end
    server cr-front:8080;
}

server {
  listen 80;
  listen [::]:80;

  # IP du serveur à modifier ici
  # pour un serveur local mettre "_"
  # pour un serveur distant, mettre l'adresse IP attendue
  server_name _; 

  # Redirection si requête sur http (80)
  return 301 https://$host$request_uri;
}

# Serveur principal avec le ssl activité
server {
    # Ecoute sur le port 443 (pour https)
  listen 443 ssl default_server;
  listen [::]:443 ssl default_server;

  # TODO mettre ici l'IP du serveur concerné
  # mettre 127.0.0.1 pour tests en local
  server_name 127.0.0.1 localhost;

  # Ajout du certificat SSL
  # Commande pour créer le certificat (avec openssl) :
  # openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout nginx-selfsigned.key -out nginx-selfsigned.crt
  # Attention à bien mettre l'IP du serveur (127.0.0.1 si vous voulez tester en local) pour le FQDN lors de la création du certificat
  ssl_certificate /etc/nginx/conf.d/server.crt;
  ssl_certificate_key /etc/nginx/conf.d/server.key;

  # TODO : limiter la taille de body client pour sécuriser vs DDOS
  client_max_body_size 0;
   
location /api {
    
    # GESTION CORS PREFLIGHT (OPTIONS)
    if ($request_method = 'OPTIONS') {
      # Ces headers sont nécessaires pour que le navigateur autorise l'appel POST/PUT/etc.
      add_header 'Access-Control-Allow-Origin' '*';
      add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
      add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
      add_header 'Access-Control-Max-Age' 1728000;
      add_header 'Content-Type' 'text/plain; charset=utf-8';
      add_header 'Content-Length' 0;
      return 204; # Code de succès pour les requêtes OPTIONS
    }

    # PROXY_PASS pour les autres méthodes (GET, POST, etc.)
    proxy_pass http://choralriff_api;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location / {
      proxy_pass http://choralriff_front;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
  }
}

